<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="138896" started-at="2020-02-19T14:16:06Z" finished-at="2020-02-19T14:18:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="138896" started-at="2020-02-19T14:16:06Z" finished-at="2020-02-19T14:18:25Z">
      <class name="com.kneat.test.Tests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.kneat.test.Tests@5119fb47]" name="setUp" is-config="true" duration-ms="9937" started-at="2020-02-19T14:16:06Z" finished-at="2020-02-19T14:16:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="FirstTest()[pri:1, instance:com.kneat.test.Tests@5119fb47]" name="FirstTest" duration-ms="127705" started-at="2020-02-19T14:16:16Z" finished-at="2020-02-19T14:18:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Limerick Strand Hotel is Listed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Limerick Strand Hotel is Listed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.kneat.pages.PageValidation.Validation(PageValidation.java:37)
at com.kneat.test.Tests.FirstTest(Tests.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FirstTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.kneat.test.Tests@5119fb47]" name="tearDown" is-config="true" duration-ms="1222" started-at="2020-02-19T14:18:24Z" finished-at="2020-02-19T14:18:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.kneat.test.Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
